/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ZynqtraBadges } from "./ZynqtraBadges";
export type { ZynqtraEvents } from "./ZynqtraEvents";
export type { ZynqtraProfile } from "./ZynqtraProfile";
