/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ZynqtraBadges__factory } from "./ZynqtraBadges__factory";
export { ZynqtraEvents__factory } from "./ZynqtraEvents__factory";
export { ZynqtraProfile__factory } from "./ZynqtraProfile__factory";
