name: Deploy contracts and pin to IPFS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Compile contracts
        run: npx hardhat compile

      - name: Deploy contracts to Arbitrum Sepolia
        run: npx hardhat run scripts/deploy.js --network arbitrumSepolia
        env:
          ARBITRUM_SEPOLIA_RPC: ${{ secrets.ARBITRUM_SEPOLIA_RPC }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}

      - name: Pin deployments to IPFS via web3.storage
        run: node scripts/pin-to-ipfs.js
        env:
          WEB3STORAGE_API_KEY: ${{ secrets.WEB3STORAGE_API_KEY }}
